version: '2'

services:
  baseimg:
    build:
      context: .
      dockerfile: Dockerfile
    image: lanparty-packages:base
  kernelimg:
    build:
      context: .
      dockerfile: Dockerfile-kernel
    image: lanparty-packages:kernel
  joki:
    image: lanparty-packages:base
    working_dir: /build/recipes/joki
    environment:
      - "GOPATH=/build/recipes/joki"
      - "GOBIN=${GOPATH}/bin"
    command: bash -c "fpm-cook clean && fpm-cook --pkg-dir /pkg"
    volumes:
      - .:/build
      - ./pkg:/pkg
  nginx:
    image: lanparty-packages:base
    working_dir: /build/recipes/nginx
    command: bash -c "fpm-cook clean && fpm-cook --pkg-dir /pkg"
    volumes:
      - .:/build
      - ./pkg:/pkg
