version: '2'

services:
  joki:
    build: .
    working_dir: /build/recipes/joki
    environment:
      - "GOPATH=/build/recipes/joki"
      - "GOBIN=${GOPATH}/bin"
    command: bash -c "fpm-cook clean && fpm-cook --pkg-dir /pkg"
    volumes:
      - .:/build
      - ./pkg:/pkg
